//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr_3.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration_for_Clients
    {
        public int id { get; set; }
        public string login_user { get; set; }
        public string password_user { get; set; }
        public int client_id { get; set; }
    
        public virtual clients clients { get; set; }
    }
}
